project:
  type: website
  output-dir: _site

website:
  title: "smkgenesis"
  site-url: https://smkgenesis.com
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: articles.qmd
        text: Articles
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
