project:
  type: website
  output-dir: _site

website:
  title: "Minkyu's Tech Blog"
  site-url: https://smkgenesis.com
  navbar:
    left:
      - href: articles.qmd
        text: Articles
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    include-in-header:
      - text: |
          <script src="page-transition.js" defer></script>
